### ISSUE TITLE
LD382A Controller nicht für RGBW steuerbar, nur EIN/AUS

### ISSUE THREAD

**Issue by jogibear9988** [iobroker-community-adapters/ioBroker.wifilight#10]
_From @strikegun on November 8, 2018 21:42_

Ich habe 7 LD382A Controller. (sunix weiß und schwarz)
Alle lassen sich ein und ausschalten. Aber RGB und W sowie Helligkeit, lässt sich nicht steuern.
Command funktioniert, aber nur der on: Befehl.

Adapter Problem oder welche Bedingungen sind nötig für den Adapter?

_Copied from original issue: soef/ioBroker.wifilight#25_

**Comment by jogibear9988** [comment]
_From @ihavenonick on November 12, 2018 14:14_

Der LD382A werkelt auch in den MagicHome Controller und da funktioniert das komplette Steuern über die DPs.

**Comment by jogibear9988** [comment]
_From @detafun on November 12, 2018 18:6_

Das gleiche bei diesen Controllern  AK001-ZJ200  ON OFF ja  Farbe nein

**Comment by jogibear9988** [comment]
_From @ak-media on November 25, 2018 8:45_

Wie wird denn der AK001-ZJ200 eingebunden? Bei mir wird das Modul zwar erkannt, erscheint aber nicht in den Objekten. Ich wäre schon froh, wenn ich schalten könnte…

**Comment by jogibear9988** [comment]
_From @strikegun on November 25, 2018 23:11_

> Wie wird denn der AK001-ZJ200 eingebunden? Bei mir wird das Modul zwar erkannt, erscheint aber nicht in den Objekten. Ich wäre schon froh, wenn ich 

Es scheint hier wohl unterschiedliche  Controller zu geben? Wie sieht deiner aus? Vielleicht sind unsere nicht kompatibel?

**Comment by jogibear9988** [comment]
_From @ak-media on November 26, 2018 8:59_

So:
![screenshot 2018-11-26 09 59 29](https://user-images.githubusercontent.com/24314548/49003326-fcc9b780-f161-11e8-8463-54460731669e.png)

**Comment by jogibear9988** [comment]
_From @strikegun on December 23, 2018 0:57_

ich habe den Fehler gefunden.
Ich hoffe es klappt euch mit euren Controllern. bei LD382A fehlte ein HEX Feld die festlegt ob rgb oder w angesteuert werden soll. Dadurch wurde jede Anfrage angelehnt. Ich kann nun mit der geänderten devices.js sehr gut steuern. Ich habe einen pull request gemacht.

**Comment by jogibear9988** [comment]
_From @detafun on December 23, 2018 8:10_

Den Controller ober deinen letzten Thread hab ich auch! Wurde die änderung jetzt auf den Github gemacht? So das ich den Adapter nur updaten muss?

**Comment by jogibear9988** [comment]
_From @ihavenonick on December 23, 2018 8:16_

Letzte Änderung war vor 2 Jahren, dürfte wohl als tot gelten dieses Projekt hier.

**Comment by jogibear9988** [comment]
_From @strikegun on December 23, 2018 8:45_

@detafun
Du kannst die Datei devices.js einfach kopieren und in den iobroker.wifilight einfügen. Mach vorher eine Kopie von der Originalen.
Dann ändere in der Instanz für dein Controller den Typ auf LD686
So kannst du schnell testen

**Comment by jogibear9988** [comment]
_From @detafun on December 31, 2018 15:33_

Ich hab es aufgegeben, ich werde die nächsten Tage die Controller auf Tasmato ändern.

**Comment by maxpd1** [comment]
Gleiche Problem mit meinen MagicHome Devices. Farbe lässt sich im Hex Format nicht steuern.
