### ISSUE TITLE
State ON wird nicht aktualisiert bei externen Befehlen

### ISSUE THREAD

**Issue by jogibear9988** [iobroker-community-adapters/ioBroker.wifilight#13]
_From @hyperbit00 on February 10, 2019 20:50_

Mindestens bei TYP AK001-ZJ100 wird der State ON nur mit neustart der Instanz aktualisiert.
Wird das LED Modul per ALEXA oder Fernbedienung oder CLOUD gesteuert, bleibt der STATE ON auf dem Wert den er zuvor hatte.

Daher wird das Modul per Fernbedienung aktivert, wechselt der State ON nicht auf TRUE.
Startet wir den Adapter jedoch neu, wird nun korrekt TRUE angezeigt.

Wo ist der Fehler?

_Copied from original issue: soef/ioBroker.wifilight#29_

**Comment by ManuelW77** [comment]
Gleiches Problem habe ich auch.

**Comment by Apollon77** [comment]
Please provide a debug level log from adater
