### ISSUE TITLE
Data Type of State is not supported 

### ISSUE THREAD

**Issue by kBrausew** [iobroker-community-adapters/ioBroker.wifilight#218]
Data Type Number ist not supported at state
wifilight.0.x_x_x_x.reachable

Device Type is LD686

complite message is:
`State value to set for "wifilight.0.192_168_178_211.reachable" has to be type "number" but received type "boolean"`

**Comment by Apollon77** [comment]
Should be fixed in upcoming new version, maybe you need to delete the affected objects once (will then be recreated)
