### ISSUE TITLE
Adapter does not start

### ISSUE THREAD

**Issue by TobiasF1986** [iobroker-community-adapters/ioBroker.wifilight#24]
The actual Adapter does not Start. iObroker and everything else is the newest Version. Tried reinstall but didn't work.

ost.raspberrypi | 2019-11-21 05:40:22.247 | info | Restart adapter system.adapter.wifilight-community.0 because enabled
-- | -- | -- | --
host.raspberrypi | 2019-11-21 05:40:22.246 | error | instance system.adapter.wifilight-community.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.raspberrypi | 2019-11-21 05:40:22.246 | error | Caught by controller[0]: at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
host.raspberrypi | 2019-11-21 05:40:22.246 | error | Caught by controller[0]: at startup (internal/bootstrap/node.js:283:19)
host.raspberrypi | 2019-11-21 05:40:22.245 | error | Caught by controller[0]: at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
host.raspberrypi | 2019-11-21 05:40:22.245 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.raspberrypi | 2019-11-21 05:40:22.244 | error | Caught by controller[0]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.raspberrypi | 2019-11-21 05:40:22.244 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:653:32)
host.raspberrypi | 2019-11-21 05:40:22.243 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.raspberrypi | 2019-11-21 05:40:22.243 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:778:30)
host.raspberrypi | 2019-11-21 05:40:22.243 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.wifilight-community/main.js:20:20)
host.raspberrypi | 2019-11-21 05:40:22.242 | error | Caught by controller[0]: at Object.exports.Adapter (/opt/iobroker/node_modules/soef/soef.js:1383:23)
host.raspberrypi | 2019-11-21 05:40:22.242 | error | Caught by controller[0]: TypeError: fns.adapter is not a function
host.raspberrypi | 2019-11-21 05:40:22.241 | error | Caught by controller[0]: ^
host.raspberrypi | 2019-11-21 05:40:22.240 | error | Caught by controller[0]: fns.adapter = fns.adapter(options);
host.raspberrypi | 2019-11-21 05:40:22.240 | error | Caught by controller[0]: /opt/iobroker/node_modules/soef/soef.js:1383
host.raspberrypi | 2019-11-21 05:40:21.435 | info | instance system.adapter.wifilight-community.0 started with pid 20807

**Comment by Firewalker99** [comment]
Same here.

**Comment by Carsten0809** [comment]
same here! any chance of getting this adapter fixed?

**Comment by Apollon77** [comment]
try "npm install soef" i the adapte directory

**Comment by foxriver76** [comment]
fixed in 1.1.0
