### ISSUE TITLE
No reaction beside on/off

### ISSUE THREAD

**Issue by maxpd1** [iobroker-community-adapters/ioBroker.wifilight#266]
**Describe the bug**  
It doesn't matter if LD686 or LD382A. I can only control on/off. All other attributes don't show any reaction. 
Even on/off is only working  90% of the time. I have to use the magichome app on smartphone in that case. There the connection is stable.
As far as I know also other users have this problem.

**To Reproduce**  
I can't give reproduction description besides changing values in this screenshot doesn't show any reaction.

![image](https://user-images.githubusercontent.com/15956503/205347629-fee4088e-62f0-479c-9f57-744a386a1464.png)

**Expected behavior**  
A change in every attribute that I change.

**Versions:**  
 - Adapter version: 1.1.4

**Comment by Apollon77** [comment]
Please set the loglevel of the instance to debug and post a debug log from such change actions as text

**Comment by maxpd1** [comment]
@Apollon77 Is the log helping you?

**Comment by Apollon77** [comment]
noeh keine Zeit gehabt ... und im log sehe ich gefühlt nichts dad irgendwas was Du sendest verarbeitet wird ... sieht eher nach "ping" commands aus ...  und data refreshs. am besten vollständiges Debug log mal posten als attachement file. vopm start und sagen über welches gerät wir reden

**Comment by Ilovegym66** [comment]
Hab ich auch… ab und zu reagiert das device nicht.. hab 24 verschiedene Magichome devices.. wenn ich was beitragen kann… ?

**Comment by maxpd1** [comment]
@Apollon77 das ist tatsächlich alles, was das Debug Log hergibt.
Ich habe den Adapter im Debug Modus neu gestartet, habe die Lampe angeschaltet (das ging diesmal), wollte die Helligkeit anpassen (das ging nicht) und im Log steht nur das gleiche wie oben gepostet.
Habe das Log nun mal auf ALLES gestellt. Vielleicht erkennt man dann mehr. Sieht aber ehrlich gesagt nicht danach aus.

[wifilight log.csv](https://github.com/iobroker-community-adapters/ioBroker.wifilight/files/10419547/wifilight.log.csv)

Das wäre wohl: 

2023-01-15 06:38:06.427  - [35msilly[39m: wifilight.0 (12660) States user redis pmessage wifilight.0.*/wifilight.0.192_168_178_74.bri:{"val":22,"ack":false,"ts":1673761086237,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1673761086237}

**Comment by maxpd1** [comment]
Any ideas?

**Comment by GermanBluefox** [comment]
Please test the new version

**Comment by GermanBluefox** [comment]
May be this PR fixed the error: https://github.com/iobroker-community-adapters/ioBroker.wifilight/pull/402

**Comment by Ilovegym66** [comment]
can be closed, it's fixed with 1.3.2 !! Thank you!
