### ISSUE TITLE
 Wifi Light Adapter im Docker Container

### ISSUE THREAD

**Issue by MikeHellracer** [iobroker-community-adapters/ioBroker.wifilight#297]
Hi, ich habe 2 Instanzen.
eine physikalische und ein Docker Container.
Leider bekomme ich den Adapter im Container zwar ans laufen, aber er findets keine Devices.
Ich vermute mal ich muss die entsprechenden Ports noch freischalten.
Leider kann ich nirgends finden auf welchem Port der Broadcast (Geräte finden) durchgeführt wird.
Es wäre nett, wenn du mir die verwendeten Ports nennen könntest.
Danke

**Comment by Apollon77** [comment]
Discovery ist UDP ... da helfen glaube ich nicht nur alleine Ports freizuschalten ... aber das ist ggf besser im Forum aufgehoben

**Comment by Ilovegym66** [comment]
entweder im Host-Modus oder mit MacVlan konfigurieren, das funktioniert sowieso am besten. Funktioniert hier einwandfrei im Docker, sofern der Adapter selbst mag..

**Comment by mcm1957** [comment]
Siehe Antwort von Ilovegym66
