### ISSUE TITLE
state wrong - must be number is boolean.. 

### ISSUE THREAD

**Issue by Ilovegym66** [iobroker-community-adapters/ioBroker.wifilight#334]
with js-controller 5.x the error appears after every re-start of the adapter ( and I let it every hour restarting, because the adapter fall in deepsleep after a while and the states of the devices are not refreshed any more.. 

`

wifilight.0 | 2023-11-04 14:13:55.401 | info | State value to set for "wifilight.0.10_1_5_203.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.361 | info | State value to set for "wifilight.0.10_1_5_214.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.341 | info | State value to set for "wifilight.0.10_1_5_209.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.340 | info | State value to set for "wifilight.0.10_1_5_206.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.340 | info | State value to set for "wifilight.0.10_1_5_200.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.334 | info | State value to set for "wifilight.0.10_1_5_215.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.333 | info | State value to set for "wifilight.0.10_1_5_220.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.333 | info | State value to set for "wifilight.0.10_1_5_205.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.333 | info | State value to set for "wifilight.0.10_1_5_217.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.333 | info | State value to set for "wifilight.0.10_1_5_201.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.332 | info | State value to set for "wifilight.0.10_1_5_212.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.331 | info | State value to set for "wifilight.0.10_1_5_208.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.328 | info | State value to set for "wifilight.0.10_1_5_207.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.328 | info | State value to set for "wifilight.0.10_1_5_213.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.327 | info | State value to set for "wifilight.0.10_1_5_216.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.327 | info | State value to set for "wifilight.0.10_1_5_210.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.327 | info | State value to set for "wifilight.0.10_1_5_218.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.327 | info | State value to set for "wifilight.0.10_1_5_221.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.326 | info | State value to set for "wifilight.0.10_1_5_219.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.324 | info | State value to set for "wifilight.0.10_1_5_202.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.319 | info | State value to set for "wifilight.0.10_1_5_211.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.262 | info | State value to set for "wifilight.0.10_1_5_204.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.231 | info | State value to set for "wifilight.0.10_1_5_221.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.230 | info | State value to set for "wifilight.0.10_1_5_220.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.230 | info | State value to set for "wifilight.0.10_1_5_219.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.230 | info | State value to set for "wifilight.0.10_1_5_218.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.229 | info | State value to set for "wifilight.0.10_1_5_217.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.229 | info | State value to set for "wifilight.0.10_1_5_216.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.228 | info | State value to set for "wifilight.0.10_1_5_215.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.228 | info | State value to set for "wifilight.0.10_1_5_214.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.227 | info | State value to set for "wifilight.0.10_1_5_213.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.227 | info | State value to set for "wifilight.0.10_1_5_212.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.225 | info | State value to set for "wifilight.0.10_1_5_211.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.224 | info | State value to set for "wifilight.0.10_1_5_210.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.223 | info | State value to set for "wifilight.0.10_1_5_209.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.221 | info | State value to set for "wifilight.0.10_1_5_208.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.221 | info | State value to set for "wifilight.0.10_1_5_207.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.220 | info | State value to set for "wifilight.0.10_1_5_206.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.218 | info | State value to set for "wifilight.0.10_1_5_205.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.218 | info | State value to set for "wifilight.0.10_1_5_204.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.216 | info | State value to set for "wifilight.0.10_1_5_202.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.215 | info | State value to set for "wifilight.0.10_1_5_201.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:55.209 | info | State value to set for "wifilight.0.10_1_5_200.reachable" has to be type "number" but received type "boolean"
wifilight.0 | 2023-11-04 14:13:53.888 | info | starting. Version 1.1.4 in /opt/iobroker/node_modules/iobroker.wifilight, node: v18.18.2, js-controller: 5.0.16
host.iobroker | 2023-11-04 14:13:49.058 | info | instance system.adapter.wifilight.0 started with pid 15938
host.iobroker | 2023-11-04 14:13:46.502 | info | instance system.adapter.wifilight.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
wifilight.0 | 2023-11-04 14:13:46.314 | info | terminating
wifilight.0 | 2023-11-04 14:13:45.812 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
wifilight.0 | 2023-11-04 14:13:45.810 | info | terminating
wifilight.0 | 2023-11-04 14:13:45.807 | info | Got terminate signal TERMINATE_YOURSELF
host.iobroker | 2023-11-04 14:13:45.806 | info | stopInstance system.adapter.wifilight.0 send kill signal
host.iobroker | 2023-11-04 14:13:45.791 | info | stopInstance system.adapter.wifilight.0 (force=false, process=true)

`

Pollintervall - for what is this, because a polling is only on restart of the adapter happened... 
![image](https://github.com/iobroker-community-adapters/ioBroker.wifilight/assets/36229898/2c661ec2-6ea8-4000-b704-4470d7500b1c)

**Comment by GermanBluefox** [comment]
Please test with 1.3.1

**Comment by Ilovegym66** [comment]
fixed with 1.3.2, thank you!
