### ISSUE TITLE
js-controller (>=35.0.0): 5.0.19

### ISSUE THREAD

**Issue by fuchs-1978** [iobroker-community-adapters/ioBroker.wifilight#372]
Der Adapter fordert:

js-controller (>=35.0.0): 5.0.19

Sollte vermutlich 5 heißen?

**Comment by Ilovegym66** [comment]
![image](https://github.com/iobroker-community-adapters/ioBroker.wifilight/assets/36229898/3a7b3cfe-6ae5-4d0d-9bc5-200f456497d3)

**Comment by mcm1957** [comment]
Shit - dachte das hab ich schon gefixed...

**Comment by mcm1957** [comment]
OK, wo hast du die 1.2.1 her? Eigentlich sollte schon seit gestern die 1.2.2 existieren und die sollte das korrigiert haben
