### ISSUE TITLE
Version 1.3.1 - no io-package.json found - error 29

### ISSUE THREAD

**Issue by Ilovegym66** [iobroker-community-adapters/ioBroker.wifilight#405]
In Version 1.3.1 the addapter is not working any more:

$ iobroker upgrade wifilight@1.3.1 --debug
Update wifilight from @1.2.2 to @1.3.1
NPM version: 10.8.1
Installing iobroker.wifilight@1.3.1... (System call)
changed 1 package in 9s276 packages are looking for funding run `npm fund` for details
Cannot find io-package.json in /opt/iobroker/node_modules/iobroker.wifilight
ERROR: Process exited with code 29

System:
Docker Buanet V10 latest, Node 20, js-controller 6.0.10, Admin 7.0.23

**Comment by mcm1957** [comment]
Please retest with upcoming 1.3.2 (currently on the way ...)

**Comment by Ilovegym66** [comment]
the error changed now:

$ iobroker add wifilight auto --host iobroker --debug

Could not read io-package.json: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.wifilight/io-package.json'

Could not read io-package.json: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.wifilight/io-package.json'

Cannot parse /opt/iobroker/node_modules/iobroker.wifilight/io-package.json: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.wifilight/io-package.json'

host.iobroker error: reading io-package.json /opt/iobroker/node_modules/iobroker.wifilight/io-package.json: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.wifilight/io-package.json'

ERROR: Process exited with code 27

**Comment by Ilovegym66** [comment]
halt, commando zurueck.. es hatte mir das Verzeichnis in node_modules gecrashed, hab per 
npm i wifilight@1.2.2 die alte wieder gerade gebogen, danach ging das update auf die 1.3.2 einwandfrei.

Jetzt aktualisiert er auch den Status von on/off super.
Vielen Dank.
