### ISSUE TITLE
V1.3.2. States are first boolean, than 0/1 numbers..

### ISSUE THREAD

**Issue by Ilovegym66** [iobroker-community-adapters/ioBroker.wifilight#406]
At the first start of the Adapter, the state reachable are fine and boolean.
After some minutes the state have a number 0 / 1 see the picture below, please:

<img width="1338" alt="Screenshot 2024-08-12 at 19 49 29" src="https://github.com/user-attachments/assets/5c4e5972-cfd5-4fb7-ba63-43988bce2efd">

Check the states, in the loops, please.

**Comment by mcm1957** [comment]
@GermanBluefox 
I do not have matching equipment. As you did the last release, could you please take a look?

**Comment by Ilovegym66** [comment]
I solved the problem by stop the adapter, delete the existing objects in the wifilight. - tree, and start the adapter again.
This looks like an issue of the old adapter version and the new one don't overwrite the existing datapoints.
Now the current version is running like expected and we can close this issue. Thank you !
