### ISSUE TITLE
Sind Geräte stromlos und werden eingeschaltet, muss man die Instanz neu starten, sonst keine Steuerung

### ISSUE THREAD

**Issue by mcuiobroker** [iobroker-community-adapters/ioBroker.wifilight#415]
Bei mir nicht, gleiches Verhalten, wie sonst auch. Ist die Instanz gestartet und einige Geräte sind stromlos, werden diese auch nach Minuten nicht erkannt, wenn man dort den Strom einschaltet.
Auch ein manueller Refresh funktioniert nicht. 
Erst nach Restart von der Instanz sind die Geräte als reachable erkannt und können geschaltet werden.

_Originally posted by @mcuiobroker in https://github.com/iobroker-community-adapters/ioBroker.wifilight/issues/407#issuecomment-2334354794_
            

Es wird auch im LOG angezeigt
```
wifilight.0 | 2024-09-07 01:22:38.481 | error | [192.168.178.64] onError: EHOSTUNREACH connect EHOSTUNREACH 192.168.178.64:5577 - will not be reconnected
-- | -- | -- | --
wifilight.0 | 2024-09-07 01:22:25.552 | error | [192.168.178.64] onError: EHOSTUNREACH read EHOSTUNREACH - will not be reconnected
wifilight.0 | 2024-09-07 01:22:18.512 | error | [192.168.178.30] onError: EHOSTUNREACH connect EHOSTUNREACH 192.168.178.30:5577 - will not be reconnected
wifilight.0 | 2024-09-07 01:22:18.512 | error | [192.168.178.32] onError: EHOSTUNREACH connect EHOSTUNREACH 192.168.178.32:5577 - will not be reconnected
wifilight.0 | 2024-09-07 01:22:12.240 | error | [192.168.178.30] onError: EHOSTUNREACH read EHOSTUNREACH - will not be reconnected
wifilight.0 | 2024-09-07 01:22:09.681 | error | [192.168.178.32] onError: EHOSTUNREACH read EHOSTUNREACH - will not be reconnected

```

Ziel: 
es wird in den angegebenen Zeitabständen geprüft ist das Gerät erreichbar, 
wenn nicht nochmal prüfen und dann aufhören. 
Nach Ablauf vom Zeitabstand, wird wieder geprüft ist das Gerät erreichbar, ...

Momentan:
es wird in den angegebenen Zeitabständen geprüft ist das Gerät erreichbar, 
wenn nicht nochmal prüfen und dann aufhören. -> Gerät wird aus Liste gelöscht und nicht mehr beim nächsten Mal geprüft.

**Comment by GermanBluefox** [comment]
Fixed in 2.0.2

**Comment by Ilovegym66** [comment]
here fixed with 2.0.2, well done!

**Comment by mcuiobroker** [comment]
Perfekt. Danke.

**Comment by mcuiobroker** [comment]
Zu früh gefreut, jetzt kommen jede Menge Warnungen, die nicht notwedig sind rein.
![image](https://github.com/user-attachments/assets/286c7568-07f9-4475-a13a-4e46dd35415e)
Nicht gefundene IPs / Geräte soll er nur einmal versuchen zu erreichen.? 
Die Warnungen hauen das LOG voll.
Hab die Instanz auf Fehler umgestellt.

**Comment by Ilovegym66** [comment]
Ist doch bei anderen Adaptern auch so, ist das device nicht erreichbar, gibts n Warning, ich würde es so lassen.

Warum schaltest du auch Devices stromlos...? Macht doch keinen Sinn..

**Comment by Ilovegym66** [comment]
Einmal am tag macht doch keinen Sinn, da kannst du auch den Adapter neu starten lassen.. 😀🖖
Oder einstellbar 😀

**Comment by mcm1957** [comment]
> Zu früh gefreut, jetzt kommen jede Menge Warnungen, die nicht notwedig sind rein. ![image](https://private-user-images.githubusercontent.com/84818934/365786063-286c7568-07f9-4475-a13a-4e46dd35415e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MTI2MjIsIm5iZiI6MTcyNTkxMjMyMiwicGF0aCI6Ii84NDgxODkzNC8zNjU3ODYwNjMtMjg2Yzc1NjgtMDdmOS00NDc1LWExM2EtNGU0NmRkMzU0MTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDIwMDUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MWVlZWI3MDc5NmRkOTI2NmY0ZmYyODc5OTM5ODk0ZjY4ZTdhZDI0YWRmNTMxM2I2YjY1YzNmZDVhMjQ1NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xnxx2GUtHEBkPYCWi9ryU4kHX_rT0w0IVT2GpjlgqfE) Nicht gefundene IPs / Geräte soll er nur einmal versuchen zu erreichen.? Die Warnungen hauen das LOG voll. Hab die Instanz auf Fehler umgestellt.

Dann mach ein diesbezügliches Issue(Feature Issue)  auf. 

Beim SNMP logge ich auch nur wenn ein Gerät nicht mehr erreichbar ist. Retries loggen nichts. Und dann wieder wenn es erreichbar wird. Ist also technisch durchaus machbar.
